// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/processor/universal/processor.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/processor/universal/processor.go -destination=internal/core/processor/universal/mock/processor.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/freeverseio/laos-universal-node/internal/platform/model"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// GetInitStartingBlock mocks base method.
func (m *MockProcessor) GetInitStartingBlock(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitStartingBlock", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitStartingBlock indicates an expected call of GetInitStartingBlock.
func (mr *MockProcessorMockRecorder) GetInitStartingBlock(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitStartingBlock", reflect.TypeOf((*MockProcessor)(nil).GetInitStartingBlock), ctx)
}

// GetLastBlock mocks base method.
func (m *MockProcessor) GetLastBlock(ctx context.Context, startingBlock uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastBlock", ctx, startingBlock)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastBlock indicates an expected call of GetLastBlock.
func (mr *MockProcessorMockRecorder) GetLastBlock(ctx, startingBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastBlock", reflect.TypeOf((*MockProcessor)(nil).GetLastBlock), ctx, startingBlock)
}

// IsEvoSyncedWithOwnership mocks base method.
func (m *MockProcessor) IsEvoSyncedWithOwnership(ctx context.Context, lastOwnershipBlock uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEvoSyncedWithOwnership", ctx, lastOwnershipBlock)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEvoSyncedWithOwnership indicates an expected call of IsEvoSyncedWithOwnership.
func (mr *MockProcessorMockRecorder) IsEvoSyncedWithOwnership(ctx, lastOwnershipBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEvoSyncedWithOwnership", reflect.TypeOf((*MockProcessor)(nil).IsEvoSyncedWithOwnership), ctx, lastOwnershipBlock)
}

// ProcessUniversalBlockRange mocks base method.
func (m *MockProcessor) ProcessUniversalBlockRange(ctx context.Context, startingBlock, lastBlock uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUniversalBlockRange", ctx, startingBlock, lastBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessUniversalBlockRange indicates an expected call of ProcessUniversalBlockRange.
func (mr *MockProcessorMockRecorder) ProcessUniversalBlockRange(ctx, startingBlock, lastBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUniversalBlockRange", reflect.TypeOf((*MockProcessor)(nil).ProcessUniversalBlockRange), ctx, startingBlock, lastBlock)
}

// RecoverFromReorg mocks base method.
func (m *MockProcessor) RecoverFromReorg(ctx context.Context, startingBlock uint64) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverFromReorg", ctx, startingBlock)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecoverFromReorg indicates an expected call of RecoverFromReorg.
func (mr *MockProcessorMockRecorder) RecoverFromReorg(ctx, startingBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverFromReorg", reflect.TypeOf((*MockProcessor)(nil).RecoverFromReorg), ctx, startingBlock)
}

// VerifyChainConsistency mocks base method.
func (m *MockProcessor) VerifyChainConsistency(ctx context.Context, startingBlock uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyChainConsistency", ctx, startingBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyChainConsistency indicates an expected call of VerifyChainConsistency.
func (mr *MockProcessorMockRecorder) VerifyChainConsistency(ctx, startingBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyChainConsistency", reflect.TypeOf((*MockProcessor)(nil).VerifyChainConsistency), ctx, startingBlock)
}
