version: 2.1

orbs:
  helm: circleci/helm@3.0.0

executors:
  cimg-base:
    docker:
      - image: cimg/base:2023.09

commands:
  build_and_push:
    description: Build and push Docker image
    parameters:
      image:
        type: string
      root:
        type: string
    steps:
      - run:
          name: Build and push Docker image
          command: |
            ./scripts/dockerize-and-push.sh freeverseio/<< parameters.image >> << parameters.root >>
  check_code_coverage:
    description: checks code coverage
    steps:
      - run:
          name: calculate code coverage
          command: |
            COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{ print $3 }' | sed 's/%//g')
            echo "Total coverage: $COVERAGE%"
            THRESHOLD=79
            if [[ ${COVERAGE%.*} -lt ${THRESHOLD%.*} ]]; then
              echo "Code coverage is less than $THRESHOLD%"
              exit 1
            fi
jobs:
  go_test:
    description: Run go tests
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Run go tests
          command: |
            go test -race -coverprofile=coverage.out ./...
      - check_code_coverage
  dockerize:
    description: Dockerize and push image
    executor: cimg-base
    parameters:
      image:
        type: string
      root:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - build_and_push:
          image: << parameters.image >>
          root: << parameters.root >>
  lint:
    description: Run linters for Go
    docker:
      - image: golangci/golangci-lint:v1.54.2
    steps:
      - checkout
      - run:
          name: Run golangci-lint
          command: |
            golangci-lint run

workflows:
  build_and_test:
    jobs:
      - lint
      - go_test:
          context: dockerhub
          filters:
            tags:
              only: /.*/
      - dockerize:
          name: dockerize_universalnode
          context: dockerhub
          image: laos-universal-node
          root: .
          filters:
            tags:
              only: /.*/
