// Code generated by MockGen. DO NOT EDIT.
// Source: internal/platform/state/tree/account/tree.go
//
// Generated by this command:
//
//	mockgen -source=internal/platform/state/tree/account/tree.go -destination=internal/platform/state/tree/account/mock/tree.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	account "github.com/freeverseio/laos-universal-node/internal/platform/state/tree/account"
	gomock "go.uber.org/mock/gomock"
)

// MockTree is a mock of Tree interface.
type MockTree struct {
	ctrl     *gomock.Controller
	recorder *MockTreeMockRecorder
}

// MockTreeMockRecorder is the mock recorder for MockTree.
type MockTreeMockRecorder struct {
	mock *MockTree
}

// NewMockTree creates a new mock instance.
func NewMockTree(ctrl *gomock.Controller) *MockTree {
	mock := &MockTree{ctrl: ctrl}
	mock.recorder = &MockTreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTree) EXPECT() *MockTreeMockRecorder {
	return m.recorder
}

// AccountData mocks base method.
func (m *MockTree) AccountData(contract common.Address) (*account.AccountData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountData", contract)
	ret0, _ := ret[0].(*account.AccountData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountData indicates an expected call of AccountData.
func (mr *MockTreeMockRecorder) AccountData(contract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountData", reflect.TypeOf((*MockTree)(nil).AccountData), contract)
}

// Checkout mocks base method.
func (m *MockTree) Checkout(blockNumber int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockTreeMockRecorder) Checkout(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockTree)(nil).Checkout), blockNumber)
}

// DeleteRootTag mocks base method.
func (m *MockTree) DeleteRootTag(blockNumber int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRootTag", blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRootTag indicates an expected call of DeleteRootTag.
func (mr *MockTreeMockRecorder) DeleteRootTag(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRootTag", reflect.TypeOf((*MockTree)(nil).DeleteRootTag), blockNumber)
}

// GetLastTaggedBlock mocks base method.
func (m *MockTree) GetLastTaggedBlock() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTaggedBlock")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTaggedBlock indicates an expected call of GetLastTaggedBlock.
func (mr *MockTreeMockRecorder) GetLastTaggedBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTaggedBlock", reflect.TypeOf((*MockTree)(nil).GetLastTaggedBlock))
}

// Root mocks base method.
func (m *MockTree) Root() common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockTreeMockRecorder) Root() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockTree)(nil).Root))
}

// SetAccountData mocks base method.
func (m *MockTree) SetAccountData(data *account.AccountData, accountAddress common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccountData", data, accountAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccountData indicates an expected call of SetAccountData.
func (mr *MockTreeMockRecorder) SetAccountData(data, accountAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccountData", reflect.TypeOf((*MockTree)(nil).SetAccountData), data, accountAddress)
}

// TagRoot mocks base method.
func (m *MockTree) TagRoot(blockNumber int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagRoot", blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// TagRoot indicates an expected call of TagRoot.
func (mr *MockTreeMockRecorder) TagRoot(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagRoot", reflect.TypeOf((*MockTree)(nil).TagRoot), blockNumber)
}
