repositories:
    - name: stable
      url: https://charts.helm.sh/stable
    - name: jetstack
      url: https://charts.jetstack.io


releases:
  - name: universalnode
    namespace: laos-bigbang
    chart: ./charts/universalnode
    values:
      - name: universalnode
      - imageTag: {{ requiredEnv "TAG" }}
      - debug: true