repositories:
    - name: stable
      url: https://charts.helm.sh/stable
    - name: jetstack
      url: https://charts.jetstack.io

environments:
  default:
    values:
    - ./environments/dev/values.yaml
  local:
    values:
    - ./environments/local/values.yaml
  development:
    values:
    - ./environments/dev/values.yaml

releases:
  - name: universalnode
    namespace: laos-bigbang
    chart: ./charts/universalnode
    createNamespace: false
    values:
      - name: universalnode
      - namespace: laos-bigbang
      - imageTag: {{ requiredEnv "TAG" }}
      - {{ toYaml .Values | nindent 8 }}
