repositories:
    - name: stable
      url: https://charts.helm.sh/stable
    - name: jetstack
      url: https://charts.jetstack.io

environments:
  default:
    values:
    - ./environments/dev/values.yaml
  local:
    values:
    - ./environments/local/values.yaml
  development:
    values:
    - ./environments/dev/values.yaml

releases:
{{ range .Values.networks }}
  - name: universalnode-{{ .name }}
    namespace: laos-bigbang
    chart: ./charts/universalnode
    createNamespace: false
    values:
      - imageTag: {{ requiredEnv "TAG" }}
      - {{ toYaml . | nindent 8 }}
      - name: universalnode-{{ .name }}
{{ end }}