releases:
    - name: universalnode-release
      namespace: {{ .Values.namespace }}
      installed: true
      createNamespace: false
      chart: .
      values:
        - name: {{ .Values.name }}
        - imageTag: {{ requiredEnv "TAG" }}
        - contractAddress: {{ .Values.name  }}
        - rpc: {{ .Values.rpc }}
        - startingBlock: {{ quote .Values.startingBlock }}
        - debug: {{ .Values.debug }}
