releases:
    - name: universalnode-release
      namespace: {{ .Values.namespace }}
      installed: true
      createNamespace: false
      chart: .
      values:
        - name: {{ .Values.name }}
        - imageTag: {{ requiredEnv "TAG" }}
        - {{ toYaml .Values | nindent 8 }}
