releases:
    - name: universalnode-release
      namespace: laos-bigbang
      installed: true
      createNamespace: false
      chart: .
      values:
        - name: {{ .Values.name }}
        - imageTag: {{ requiredEnv "TAG" }}
        - debug: {{ .Values.debug }}
