apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
      - name: universalnode
        image: freeverseio/laos-universal-node:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5001
            name: rpc
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        command: [ "./universalnode" ]
        args: [ -contract={{ .Values.contractAddress }},
        -rpc={{ .Values.rpc }} ]
