apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
      - name: universalnode
        image: freeverseio/laos-universal-node:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5001
            name: rpc
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        command: [ "./universalnode" ]
        args: [ -contracts={{ .Values.contracts }},
                -rpc={{ .Values.rpc }},
                -evo_rpc={{ .Values.evoRpc }},
                -evo_contract={{ .Values.evoContracts }},
                {{ if hasKey .Values  "startingBlock" }}
                -starting_block={{ .Values.startingBlock }},
                {{ end }}
                {{ if hasKey .Values  "blocksMargin" }}
                -blocks_margin={{ .Values.blocksMargin }},
                {{ end }}
                {{ if hasKey .Values  "blocksRange" }}
                -blocks_range={{ .Values.blocksRange }},
                {{ end }}
                {{ if hasKey .Values  "evoStartingBlock" }}
                -starting_block={{ .Values.evoStartingBlock }},
                {{ end }}
                {{ if hasKey .Values  "evoBlocksMargin" }}
                -blocks_margin={{ .Values.evoBlocksMargin }},
                {{ end }}
                {{ if hasKey .Values  "evoBlocksRange" }}
                -blocks_range={{ .Values.evoBlocksRange }},
                {{ end }}
                {{ .Values.debug | ternary "-debug" "" }}
              ]
