apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      # allow user "nobody" to write to /app/.universalnode https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
      securityContext:
        fsGroup: 65534
      containers:
      - name: universalnode
        image: freeverseio/laos-universal-node:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5001
            name: rpc
        resources:
          requests:
            memory: "3Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
        command: [ "./universalnode" ]
        args: [ -contracts={{ .Values.contracts }},
                -storage_path=/app/.universalnode,
                -rpc={{ .Values.rpc }},
                -evo_rpc={{ .Values.evoRpc }},
                {{ if hasKey .Values  "startingBlock" }}
                -starting_block={{ .Values.startingBlock }},
                {{ end }}
                {{ if hasKey .Values  "blocksMargin" }}
                -blocks_margin={{ .Values.blocksMargin }},
                {{ end }}
                {{ if hasKey .Values  "blocksRange" }}
                -blocks_range={{ .Values.blocksRange }},
                {{ end }}
                {{ if hasKey .Values  "evoStartingBlock" }}
                -evo_starting_block={{ .Values.evoStartingBlock }},
                {{ end }}
                {{ if hasKey .Values  "evoBlocksMargin" }}
                -evo_blocks_margin={{ .Values.evoBlocksMargin }},
                {{ end }}
                {{ if hasKey .Values  "evoBlocksRange" }}
                -evo_blocks_range={{ .Values.evoBlocksRange }},
                {{ end }}
                {{ .Values.debug | ternary "-debug" "" }}
              ]
        volumeMounts:
        - name: storage
          mountPath: /app/.universalnode
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
